const columnNames = {
  hsCode: "HS Code",
  vehicleType: "Vehicle Type",
  fuelType: "Fuel Type",
  engineCC: "CC/Kw",
  tax: "Total Tax",
  yellowBookPrice: "Yellow",
  dipFOB: "DIP FOB",
  freight: "Freight",
  insurance: "Insurance",
  other: "Other",
  cifJPY: "CIF JPY",
  cifLKR: "CIF LKR",
  cm3: "CM³",
  generalDuty: "Gen. Duty",
  surcharge: "Surcharge",
  pPerUnitLKR: "P/Unit (LKR)",
  pPerCM3LKR: "P/CM³ (LKR)",
  pal: "PAL (0%)",
  ssl: "SSL (2.5%)",
  vat: "VAT (18%)",
  luxuryTax: "Luxury Tax",
  rateCurrency: "Currency",
  cifJPY1: "CIF JPY1",
  cifLKR1: "CIF LKR1",
  exchangeRate: "Exchange Rate",
  generalDutyRate: "General Duty Rate",
  surchargeRate: "Sur. Rate",
  vatRate: "Vat Rate",
  luxTaxFD: "Lux Tax FD",
  luxuryTaxRateValue: "Luxury Tax Rate Value",
  luxuryTaxCalculation: "Luxury Tax Calculation",
};

export default columnNames;
